name: Wpm
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Log in to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Build and push Management container image'
        run: |
          docker build src -f src/Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}

      - name: 'Build and push Clinic container image'
        run: |
          docker build src -f src/Wpm.Clinic/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ github.sha }}

      - name: Deploy to Management Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUsername: ${{ secrets.ACR_USERNAME }}
            acrPassword: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm-management
            resourceGroup: wpm
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}
            environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug

      - name: Deploy to Clinic Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUsername: ${{ secrets.ACR_USERNAME }}
            acrPassword: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm-clinic
            resourceGroup: wpm
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ github.sha }}
            environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug, Wpm__ManagementUri=http://wpm-management