name: Wpm
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Log in to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Build and push container image'
        run: |
          docker build src -f src/Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUsername: ${{ secrets.ACR_USERNAME }}
            acrPassword: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm_management
            resourceGroup: wpm
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}